### ISSUE TITLE
Submenu support

### ISSUE THREAD

**Issue by fabiocaccamo** [balzss/luxbar#14]
Is it in your plans to provide submenu support?

**Comment by balzss** [comment]
Right now you can do dropdowns like so: 
`    <div class="luxbar luxbar-static">
        <input type="checkbox" id="luxbar-checkbox" class="luxbar-checkbox">
        <div class="luxbar-menu luxbar-menu-material-cyan">
            <ul class="luxbar-navigation">
                <li class="luxbar-header">
                    <a class="luxbar-brand" href="#">LUXBAR</a>
                    <label class="luxbar-hamburger luxbar-hamburger-doublespin" for="luxbar-checkbox"> <span></span> </label>
                </li>
                <li class="luxbar-item"><a href="#">Home</a></li>
                <li class="luxbar-item"><a href="#">Demo</a></li>
                <li class="luxbar-item dropdown"><a href="#">Dropdown Users</a>
                    <ul>
                        <li class="luxbar-item" ><a href="#">Max</a></li>
                        <li class="luxbar-item" ><a href="#">Edgar</a></li>
                        <li class="luxbar-item" ><a href="#">John</a></li>
                    </ul>
                </li>
                <li class="luxbar-item active"><a href="#">FAQ</a></li>
                <li class="luxbar-item"><a href="#">Download</a></li>
                <li class="luxbar-item"><a href="#">Github</a></li>
            </ul>
        </div>
    </div>`

And I'm planning to introduce "menu-groups" to have more flexibility with alignements. Is this the kind of thing you are looking for?

**Comment by fabiocaccamo** [comment]
Yes, thanks
