### ISSUE TITLE
Responsive Bug

### ISSUE THREAD

**Issue by hirschy** [balzss/luxbar#15]
When the mobile menu is open and the screen is expanded past 767px the .luxbar-menu is still open. The following applied after line 382 should solve that for you.

` #luxbar-checkbox:checked ~ .luxbar-menu {
    height: auto;
    }
`

*I'm aware it's probably not going to pop up often, but figured it'd help.

**Comment by balzss** [comment]
Fixed in 3031f9d44b26503b2e2cd71d0433072bc5528fc9.
