### ISSUE TITLE
Mobile menu stays open and full screen if resize browser up after opening

### ISSUE THREAD

**Issue by dswebdotnet** [balzss/luxbar#18]
Hi there

Firstly, lovely simple menu.

One thing i often check with similar menus is if the mobile drop menu/overlay closes after you resize up the browser. 

steps to recreate:
1. resize down the browser down to mimic a mobile
2. open the menu
3. resize the browser back up to desktop size and notice the menu overlay is still open/full screen although the nav items have returned to desktop view

Should be fixable with a mediaquery to remove the overlay.

Thanks for great work.

**Comment by balzss** [comment]
Hi, thanks for reporting this issue. Have you noticed this behavior with the demo site only or with the actual package? Because I remeber fixing this a couple days ago but the demo page didn't get updated.

**Comment by dswebdotnet** [comment]
Hi there, 

Just on the demo page, I haven't tried the source package yet, but I can later to confirm and update this ticket.

cheers

**Comment by balzss** [comment]
Ok, I will update the demo page when I get home :)

**Comment by balzss** [comment]
Done, now the demo page uses the correct version and closes when screen width changes.
