### ISSUE TITLE
Generated checkbox <input> element from menu builder missing luxbar-checkbox class

### ISSUE THREAD

**Issue by smallsaucepan** [balzss/luxbar#28]
Hi. In the code generated by the menu building page, the checkbox <input> element is missing the luxbar-checkbox class below:

`<input type="checkbox" id="luxbar-checkbox" class="luxbar-checkbox">`

**Comment by balzss** [comment]
Thanks for pointing this out. I'll fix ASAP.

**Comment by balzss** [comment]
fixed in 70035a2eca41fe748cf5b9a493d0451e318a06af
