### ISSUE TITLE
Use autoprefixer

### ISSUE THREAD

**Issue by Pustur** [balzss/luxbar#3]
Since this project uses some features that are not yet safe to use without prefixes (namely flexbox) i would suggest to either include autoprefixer or making it mandatory to run the css through [autoprefixer online](https://autoprefixer.github.io/) before committing / contributing.

**Comment by Tiliavir** [comment]
Done here: https://github.com/balzss/luxbar/pull/7
sorry for the mess so - was not intending to file a PR initially ;-)

**Comment by Pustur** [comment]
Fixed in PR #7
