### ISSUE TITLE
Supported browsers and versions

### ISSUE THREAD

**Issue by websitesbymark** [balzss/luxbar#31]
I cant find any information about what the browser support is like for this project.

I am currently creating my own simple css grid system and would like to suggest to people who use it, to use your navigation, but unsure what to say is supported.

Many thanks in advance.

**Comment by balzss** [comment]
Hi, right now it's tested on every major browser(safari, chrome, firefox) however there is a minor bug on chrome for windows, for more info see (this)[https://github.com/balzss/luxbar/issues/5 ])

**Comment by websitesbymark** [comment]
Thanks for the reply. 

I was actually more interested in for instance if someone was running for instance a very old iphone or android phone, if it would behave itself and if not how it degraded. (I hope this makes sense.)

For my needs I simply need something that only is single tier and expands and collapses on very small screens. Im also looking for something light and that does not need JS or JQuery, but would work on older browsers.. From the demo this looks great and for me its a toss up between this and the menu component of pure.css

**Comment by balzss** [comment]
Oh OK. So the CSS features that might be unsupported are flexbox and maybe translate. As far as I know it works fine on old phones if the browser is updated but I'm not sure how regularly it's done on stock browsers. I hope this helped.
