### ISSUE TITLE
Closing menu

### ISSUE THREAD

**Issue by antoinelon** [balzss/luxbar#34]
hello
this is great work you have done. thanks a lot.
I got a question: is there an easy way to have the menu which will close automatically when clicking on any of link on a portable device instead of having to close it manually?
thanks for your help

**Comment by balzss** [comment]
Hi,
Sorry for the late response. You have to use javascript in order to achive what you described. For example in JQuery:
``` javascript
$('.luxbar-item').click(function(event) {
    $('#luxbar-checkbox').prop('checked', false);
}
```
But it can be done in pure js as well. I hope this helped :)

**Comment by mwoz123** [comment]
My plain js proposal: 
~~[...document.getElementsByClassName('luxbar-item')].forEach(item =>item.addEventListener('click', () => document.getElementById("luxbar-checkbox").checked = false));~~

Edit: @balzss thanks. I'd just noticed it doesn't work on mobile.

**Comment by balzss** [comment]
Thanks for adding this. I would slightly modify it like this:
`document.querySelectorAll('.luxbar-item').forEach(item => item.addEventListener('click', () => document.querySelector('#luxbar-checkbox').checked = false));`

**Comment by mwoz123** [comment]
actually the one above doesn't fork for IE11. 
Looks like this one does: 
```
[].forEach.call(
document.querySelectorAll('.luxbar-item') , 
function (item) { item.addEventListener('click', function() {document.querySelector('#luxbar-checkbox').checked = false; }) 
});
```

**Comment by mwoz123** [comment]
IE11 don't allow i.e. arrow functions :(
This works also in IE11: 

```
var forEach = function (array, callback, scope) {
	for (var i = 0; i < array.length; i++) {
		callback.call(scope, i, array[i]);
	}
};

var menuItems = document.querySelectorAll('.luxbar-item');
forEach(menuItems, function (index, item) {
	item.addEventListener('click', function () {
		document.querySelector('#luxbar-checkbox').checked = false;
	});
});
```
