### ISSUE TITLE
Checkbox is visible | close

### ISSUE THREAD

**Issue by precinct13** [balzss/luxbar#35]
Hi,

first i want to thank you for this nice menu. I just got a little problem and i don't know how to fix it or why it is happening at my project.

When i implement the menu with the demo builder i always have the visible checkbox above the menu on my site. Could be something on my side, but maybe someone has an idea how to fix it.

![checkboxvisible](https://user-images.githubusercontent.com/17931003/31392057-921dbe90-add8-11e7-910e-87c058289d4e.JPG)

**The problem was on my side of the. I used a grid which messed with the CSS list properties.**

**Comment by kapena** [comment]
That's interesting. So you are copying the code from the demo into your project and then the check box appears visible? Have you resolved this issue ?

**Comment by kapena** [comment]
You can remove the check box simply by calling the class `luxbar-checkbox` and removing it like so. This is a temp fix to the issue.
````css
.luxbar-checkbox {
    display: none;
}
````
