### ISSUE TITLE
Trying to implement luxbar into my React app JS

### ISSUE THREAD

**Issue by sjollois** [balzss/luxbar#36]
Hello, 

I am trying to implement Luxbar into my React App JS but it isn't working and show me this in my browser : 
![capture d ecran 2018-02-12 a 11 25 01](https://user-images.githubusercontent.com/23353046/36092501-e25133a8-0fe7-11e8-973c-17ab828c88f5.png)

my code is : 

![capture d ecran 2018-02-12 a 11 30 14](https://user-images.githubusercontent.com/23353046/36092548-01b26f3c-0fe8-11e8-80ab-b832c38d1e5a.png)

![capture d ecran 2018-02-12 a 11 34 04](https://user-images.githubusercontent.com/23353046/36092699-92293d7a-0fe8-11e8-94a6-934d6a38640f.png)

my packagejonson is : 

![capture d ecran 2018-02-12 a 11 31 57](https://user-images.githubusercontent.com/23353046/36092714-9cbf5792-0fe8-11e8-8538-e8c955257b5e.png)

Can you help me please ! Thank you very much !

**Comment by balzss** [comment]
Did you include the luxbar.css file in your index.html?

**Comment by balzss** [comment]
Closing this for now. Reopen if you still have the issue.

**Comment by bernagl** [comment]
Give a try: https://github.com/bernagl/react-luxbar
