### ISSUE TITLE
Hamburger menu doesn't work

### ISSUE THREAD

**Issue by ctuxboy** [balzss/luxbar#41]
Hello,

Installed this awesome navbar!
On desktop all works perfect, but on mobile (<768px), i see a 'normal' menu-list (li) and there is no 'hamburger' for toggle the menu.

**Comment by balzss** [comment]
Have you included the [viewport meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) in you page?

**Comment by ctuxboy** [comment]
Hi @balzss ,

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Here you can see a temporaly test-website:
http://interieur.webkusthosting.be/

**Comment by balzss** [comment]
Did you use the demo page to generate the luxbar html code?  I see that you are missing the color definition but you probably miss something else as well and that's why it doesn't open and close properly. Try to use the code from [this page](https://balzss.github.io/luxbar/) without any modification and see if that works.

**Comment by ctuxboy** [comment]
yes,
i do two adjustments:
- removed the color 'luxbar-menu-dark' and adding my own color.
- removed the checkbox `<input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/> `

Now it works adding this elements, but the checkbox breaks the layout, see the test-website.

**Comment by ctuxboy** [comment]
Solve the issue.
Adding 'display: none' to the **checkbox** element.

`<input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox" style="display:none"/>`

Now it works perfect!

Thanks for the fast support :)

**Comment by balzss** [comment]
The checkbox is needed to work properly but it should be hidden by default. Maybe you overwrote the rule or something but I'm glad you got it sorted out :)

**Comment by ctuxboy** [comment]
Yes, i think the grid framework overwrite the checkbox: https://milligram.io/

But it works ;)
