### ISSUE TITLE
Luxbar mobile menu don't close after click on menu item (with inner anchor)

### ISSUE THREAD

**Issue by mwoz123** [balzss/luxbar#42]
I've anchor with `#` in menu like this:
```
(...)
<li class="luxbar-item"><a href="#place-in-current-html">Item 1</a></li>
(... couple more menu items here)
```

then at the bottom of my Single Page app I've :
```
<div id="place-in-current-html"> A element where screen is scroll downed</div>
```

As expected it scrolls down to `place-in-current-html` div on both pc and mobile. 

But on mobile (when menu is displayed after being hidden under "hamburger" icon), when you click on `Item 1` menu, even thought page is scrolled to right element (as expected), 
fullscreen luxbar menu hovers the page (until manually click on `X` button). 

I think it should be hidden after click on link (`Item 1`), otherwise it seems menu is not working (on mobile) for end users.

Could you solve that?

**Comment by balzss** [comment]
It would require javascript code to do that which I don't want to add to a pure CSS library. However you can totally add that bit of code yourself [like it was previously suggested](https://github.com/balzss/luxbar/issues/19#issuecomment-280913636) or something similar with vanilla javascript.

It seems like a popular feature request so I might address this in the FAQ page.

**Comment by mwoz123** [comment]
thanks. Closing then.

**Comment by mwoz123** [comment]
Plain JS code that works also on IE11: https://github.com/balzss/luxbar/issues/34#issuecomment-461509775
