### ISSUE TITLE
Menu issues.

### ISSUE THREAD

**Issue by billthecreator** [balzss/luxbar#8]
Resize window to show the menu icon. Then open the menu, and go back to full screen or a bigger window size. The menu is now full screen and can't escape.

**Comment by balzss** [comment]
You can reset the menu by refreshing the page. I'm aware of the fact that this is not user friendly but I can't think of an actual situation when the user's screen is actively resizing during the visit of the page. But I could be wrong so please correct me if I'm missing something.

**Comment by Pustur** [comment]
I agree with @balzss, normal users don't resize the page nearly as often as developers do so this issue is not really worth fixing in my opinion.

**Comment by billthecreator** [comment]
Rotating a larger device maybe?

I know its not super important, just thought I'd point it out.
No worries.

**Comment by Pustur** [comment]
@billthecreator oh yeah i didn't think of that, it could be a problem i guess.

**Comment by balzss** [comment]
That's a very good point and I see how that could be a problem. As I'm looking into it now, it seems easy to fix it (need to add  `.luxbar-menu { height: 58px !important;}` when screen width  > 786px) so I'll do it as soon as I get home. :)

**Comment by billthecreator** [comment]
:) Glad I could help!

**Comment by balzss** [comment]
Fixed in 4f45961
